### ISSUE TITLE
5.ii SimulatorCloudRunner.ps1 line 2: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by GraceFu** [lowndesc/industryx#5]
Hi, I got the error when I tried to run SimulatorCloudRunner.ps1:
```
./SimulatorCloudRunner_fix.ps1: line 2: syntax error near unexpected token `newline'
./SimulatorCloudRunner_fix.ps1: line 2: `param ('
```
Could you probably help me with this?

Thanks,
Grace

**Comment by lowndesc** [comment]
> Hi, I got the error when I tried to run SimulatorCloudRunner.ps1:
> 
> ```
> ./SimulatorCloudRunner_fix.ps1: line 2: syntax error near unexpected token `newline'
> ./SimulatorCloudRunner_fix.ps1: line 2: `param ('
> ```
> 
> Could you probably help me with this?
> 
> Thanks,
> Grace

This may be an issue with text file encoding. Try testing the file locally in Powershell to see if it throws the same error.

**Comment by GraceFu** [comment]
> > Hi, I got the error when I tried to run SimulatorCloudRunner.ps1:
> > ```
> > ./SimulatorCloudRunner_fix.ps1: line 2: syntax error near unexpected token `newline'
> > ./SimulatorCloudRunner_fix.ps1: line 2: `param ('
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you probably help me with this?
> > Thanks,
> > Grace
> 
> This may be an issue with text file encoding. Try testing the file locally in Powershell to see if it throws the same error.

Yeah it didn't throw this error when I run it locally. 
I tried to look it up but didn't manage to solve it. Could you provide any insights? Thanks! 
(I've checked and there are indeed only `\n` not `\r` or `\r\n`...)

**Comment by GraceFu** [comment]
Sorry I just realized that I did not switch from Bash to Powershell, which causes this "error"... It's all good now!
