### ISSUE TITLE
Failure when creating Simulated Devices

### ISSUE THREAD

**Issue by lmjohnhu** [lowndesc/industryx#6]
Hi Chris,

Could you help look into this issue? I've strictly followed the name format of the resource group but it still doesn't work. Thanks!

<img width="949" alt="IoT Devices execute command failure" src="https://user-images.githubusercontent.com/84268365/128030302-fc1b57a9-f36e-4fb1-8979-08a5de0bfd88.PNG">

**Comment by daniloavanade** [comment]
> Hi Chris,
> 
> Could you help look into this issue? I've strictly followed the name format of the resource group but it still doesn't work. Thanks!
> 
> <img alt="IoT Devices execute command failure" width="949" src="https://user-images.githubusercontent.com/84268365/128030302-fc1b57a9-f36e-4fb1-8979-08a5de0bfd88.PNG">


Hello lmjohnhu,

This issue was solved for me me when I put the -IotHubConnectionString value between quotation marks " "

<img width="1915" alt="Screenshot 2021-08-04 111021" src="https://user-images.githubusercontent.com/87956856/128110687-bddc1f38-229e-4194-854a-427d9947e0af.png">

**Comment by rosemarielesana** [comment]
Hi lmjohnlu,

Open the editor in Azure Cloud Shell. The filename might have been renamed after the upload. Use that name when you execute the command and put quotes on the connection string.

![image](https://user-images.githubusercontent.com/40256537/128116120-a9d88ba2-f037-4fad-9486-64883157c6fc.png)

**Comment by lmjohnhu** [comment]
Thank you both for your help!
