### ISSUE TITLE
6.vii. Extra Space in SQL query

### ISSUE THREAD

**Issue by GraceFu** [lowndesc/industryx#7]
Hi Chris,

Just wanna bring it up that in Updating A Twin section, there is an extra space in the SQL query. Currently it is 
`SELECT * FROM DIGITAL TWINS WHERE IS_OF_MODEL('dtmi:isa95:core:Asset;1')`
and it should be
`SELECT * FROM DIGITALTWINS WHERE IS_OF_MODEL('dtmi:isa95:core:Asset;1')`

Hope it helps!
Best,
Grace

**Comment by lowndesc** [comment]
Thanks - now fixed

**Comment by lowndesc** [comment]
Fixed
